name: Java CI with Gradle
run-name: Running
on:
  push:
    branches:
      - production
      - 'releases/**'
env:
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: journal-cicd-bucket
  AWS_CODE_DEPLOY_APPLICATION: journal-cicd
  AWS_CODE_DEPLOY_GROUP: journal-cicd-group

permissions:
  contents: read

jobs:
  build-with-gradlew:

    runs-on: ubuntu-20.04

    steps:
      - name: main 브랜치로 이동
        uses: actions/checkout@v3
        with:
          ref: main

      - name: jdk 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: 권한 부여
        run: chmod +x ./gradlew
      - name: 빌드
        run: ./gradlew clean build -x test
      - name: aws credentials 설정
        uses: aws-action/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.CICD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secret.CICD_SECERT_KEY }}
      - name: S3에 업로드
        run: aws deploy push --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} --ignore-hidden-files --s3-location s3://$AWS_S3_BUCKET/journal-backend/$GITHUB_SHA.zip --source .
      - name: ec2에 배포
        run: aws deploy create-deployment --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name ${{ env.AWS_CODE_DEPLOY_GROUP }} --s3-location bucket=$AWS_S3_BUCKET,key=journal-backend/$GITHUB_SHA.zip, bundleType=zip